### ISSUE TITLE
Dar acceso a los responsables del calendario por curso

### ISSUE THREAD

**Issue by mroman42** [libreim/calendar-deprecated#8]
Simplemente comprobar que cualquiera queriendo mantener un calendario tiene acceso a ellos. Creo que siguen manteniendo el calendario ahora mismo, por #3:

   - En segundo, @jmml97 y @fjsaezm.
   - En tercero, @mx-psi.

Si alguien quiere encargarse del calendario en alguno de los cursos que no he escrito o si alguien no puede mantenerlo, puede comentarlo en esta issue.

**Comment by oxcar103** [comment]
Si vas a actualizar esta issue anualmente, debería aparecer el curso al que hace mención en la cabecera, no?

El 4/12/2016 16:21, "Mario Román" <notifications@github.com> escribió:

Simplemente comprobar que cualquiera queriendo mantener un calendario tiene
acceso a ellos. Creo que siguen manteniendo el calendario ahora mismo, por
#3 <https://github.com/libreim/calendar/issues/3>:

   - En segundo, @jmml97 <https://github.com/jmml97> y @fjsaezm
   <https://github.com/fjsaezm>.
   - En tercero, @mx-psi <https://github.com/mx-psi>.

Si alguien quiere encargarse del calendario en alguno de los cursos que no
he escrito o si alguien no puede mantenerlo, puede comentarlo en esta issue.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/libreim/calendar/issues/8>, or mute the thread

**Comment by mroman42** [comment]
Creo que lo mejor va a ser ir cerrando los calendarios centralizados y dar permisos de administración a gente de cada curso. Que cada promoción tenga un calendario y lo gestione en lugar de estar rotando calendarios y que no dependan de la cuenta de libreim. Así que esta issue no tiene más recorrido.
